-- Add Shat-tila Ekadashi story from Bhavishya Uttara Purana
-- The six uses of sesame seeds

BEGIN;

UPDATE ekadashi_info SET
  glory_text_uk = E'**Бгавішья Уттара Пурана**\n\n**Шість способів використання кунжуту (Шат-тіла)**\n\nНазва «Шат-тіла» означає «шість кунжутів». У цей екадаші людина повинна:\n\n1. **Омитися** у воді, змішаній з кунжутними зернами\n2. **Нанести** на тіло кунжутну пасту\n3. **Здійснити** вогняне жертвоприношення з кунжутом\n4. **Запропонувати** предкам воду, змішану з кунжутом\n5. **Їсти** кунжутні зерна\n6. **Вільно роздавати** кунжутні зерна\n\nЗавдяки цим діянням всі наслідки гріховних вчинків знищуються.\n\n**Діалог мудреців Далбг''ї та Пуластьї**\n\nМудрець Далбг''я запитав: «Люди здійснюють різні гріховні вчинки — вбивають брахманів та насолоджують свої почуття в цьому тлінному світі. Як вони можуть звільнитися від пекельного стану?»\n\nМудрець Пуластья відповів: «У день екадаші людина повинна поклонятися Верховному Господу, молячись так:\n\n*«О Господь Джанардана! О найбільш милостивий Господь Крішна, Ти — рятівник грішників. Будь ласка, будь милостивим до тих, хто потонув в океані матеріального існування. О Верховний Брахман! О Володар всесвіту! Прийми моє поклоніння, і нехай прийме його Твоя супруга Лакшмідеві.»*\n\nДаруючи кунжутні зерна, людина отримує можливість протягом багатьох років жити в раю.»\n\n**Історія жінки-брахміні**\n\nКолись жила жінка-брахміні. Вона суворо дотримувалась обітниці екадаші та поклонялась Господу. Постійно дотримуючись різних обітниць, вона стала слабкою та худою. Хоча вона дарувала подарунки бідним брахманам та незаміжнім дівчатам, **вона ніколи не задовольняла брахманів та напівбогів підношенням їм зерен**.\n\n**Випробування від Крішни**\n\nБажаючи випробувати цю брахміні, Господь Крішна прийняв вигляд жебрака і прийшов до її дому. Жінка запитала: «О брахман! Звідки ти прийшов?» Крішна вдав, що не чує її, і знову попросив милостиню. Жінка розгнівалась, взяла пригорщу глини і поклала її в посудину для підношень. Після цього Крішна повернувся до Своєї обителі.\n\n**На Вайкунтсі**\n\nЗавдяки своїм аскезам жінка-брахміні також потрапила до обителі Господа. Хоча в неї був прекрасний дім, **через те, що вона запропонувала Крішні шматок глини, в цьому домі не було ні багатства, ні зерна**.\n\nЖінка звернулась до Крішни: «Я здійснювала суворі аскези, дотримувалась обітниць і поклонялась Господу Вішну. Чому ж тоді я позбавлена зерна та багатства?»\n\n**Порада Господа**\n\nГосподь відповів: «Коли дружини напівбогів прийдуть до твого дому, запитай їх про славу Шат-тіла Екадаші. Не відкривай двері, доки вони не завершать розповідь.»\n\n**Результат**\n\nОдна з дружин напівбогів розповіла про славу цього екадаші. Дотримуючись настанов, брахміні дотрималась обітниці Шат-тіла Екадаші. Завдяки цьому **вона стала прекрасною, сяючою власницею достатньої кількості зерна, багатства та золота**.\n\nОднак ніхто не повинен дотримуватись цього екадаші, рухомий жадібністю. Завдяки слідуванню цьому екадаші невезіння та бідність відходять.',

  glory_text_en = E'**Bhavishya Uttara Purana**\n\n**Six Uses of Sesame Seeds (Shat-tila)**\n\nThe name "Shat-tila" means "six sesames." On this Ekadashi one should:\n\n1. **Bathe** in water mixed with sesame seeds\n2. **Apply** sesame paste to the body\n3. **Perform** fire sacrifice with sesame\n4. **Offer** water mixed with sesame to ancestors\n5. **Eat** sesame seeds\n6. **Freely distribute** sesame seeds\n\nThrough these actions all consequences of sinful deeds are destroyed.\n\n**Dialogue of Sages Dalbhya and Pulastya**\n\nSage Dalbhya asked: "People commit various sinful acts—kill brahmins and enjoy their senses in this mortal world. How can they be freed from the hellish state?"\n\nSage Pulastya replied: "On the day of Ekadashi one should worship the Supreme Lord, praying thus:\n\n*"O Lord Janardana! O most merciful Lord Krishna, You are the savior of sinners. Please be merciful to those who have drowned in the ocean of material existence. O Supreme Brahman! O Lord of the universe! Please accept my worship, and may Your consort Lakshmidevi accept it."*\n\nBy giving sesame seeds, one receives the opportunity to live in heaven for many years."\n\n**The Story of the Brahmin Woman**\n\nOnce there lived a brahmin woman. She strictly observed the vow of Ekadashi and worshiped the Lord. Constantly observing various vows, she became weak and thin. Although she gave gifts to poor brahmins and unmarried girls, **she never satisfied brahmins and demigods by offering them grains**.\n\n**Krishna''s Test**\n\nDesiring to test this brahmin woman, Lord Krishna assumed the form of a beggar and came to her house. The woman asked: "O brahmin! Where have you come from?" Krishna pretended not to hear her and again asked for alms. The woman became angry, took a handful of clay, and put it in His begging bowl. After this, Krishna returned to His abode.\n\n**On Vaikuntha**\n\nDue to her austerities, the brahmin woman also reached the Lord''s abode. Although she had a beautiful house, **because she had offered Krishna a piece of clay, there was neither wealth nor grain in that house**.\n\nThe woman addressed Krishna: "I performed severe austerities, observed vows, and worshiped Lord Vishnu. Why then am I deprived of grain and wealth?"\n\n**The Lord''s Advice**\n\nThe Lord replied: "When the wives of the demigods come to your house, ask them about the glory of Shat-tila Ekadashi. Do not open the door until they complete the narration."\n\n**The Result**\n\nOne of the demigods'' wives narrated the glory of this Ekadashi. Following the instructions, the brahmin woman observed the vow of Shat-tila Ekadashi. As a result, **she became beautiful, radiant, and the owner of sufficient grain, wealth, and gold**.\n\nHowever, no one should observe this Ekadashi driven by greed. By following this Ekadashi, misfortune and poverty depart.',

  story_uk = E'Жінка-брахміні суворо постила та здійснювала аскези, але ніколи не годувала голодних зерном.\n\nОдного дня Крішна прийшов до неї як жебрак. Розгнівана жінка кинула в Його посудину для підношень пригорщу глини.\n\nЗавдяки аскезам вона потрапила на Вайкунтху, але в її прекрасному домі не було ні зерна, ні багатства — все через ту пригорщу глини.\n\nЗа порадою Крішни, вона дізналась від дружин напівбогів про славу Шат-тіла Екадаші. Дотримавшись його правильно — з шістьма способами використання кунжуту — вона стала прекрасною та заможною.\n\nМораль: аскези без щедрості не приносять повного плоду. Потрібно не лише постити, а й давати.',

  story_en = E'A brahmin woman strictly fasted and performed austerities, but never fed the hungry with grain.\n\nOne day Krishna came to her as a beggar. The angry woman threw a handful of clay into His begging bowl.\n\nDue to her austerities, she reached Vaikuntha, but in her beautiful house there was neither grain nor wealth—all because of that handful of clay.\n\nFollowing Krishna''s advice, she learned about the glory of Shat-tila Ekadashi from the wives of the demigods. Observing it properly—with the six uses of sesame—she became beautiful and prosperous.\n\nMoral: austerities without generosity do not bear full fruit. One must not only fast but also give.',

  benefits_uk = E'• Знищення наслідків гріховних вчинків\n• Можливість жити в раю багато років\n• Усунення невезіння та бідності\n• Шестикратні благословення кунжуту\n• Задоволення брахманів та напівбогів\n• Багатство, зерно, процвітання',

  benefits_en = E'• Destruction of consequences of sinful deeds\n• Opportunity to live in heaven for many years\n• Removal of misfortune and poverty\n• Sixfold blessings of sesame\n• Satisfaction of brahmins and demigods\n• Wealth, grain, prosperity',

  glory_source = 'Bhavishya Uttara Purana',

  presiding_deity_uk = 'Господь Джанардана (Крішна), Лакшмідеві',
  presiding_deity_en = 'Lord Janardana (Krishna), Lakshmidevi',

  recommended_activities_uk = E'**Шість способів використання кунжуту:**\n\n1. Омивання у воді з кунжутом\n2. Нанесення кунжутної пасти на тіло\n3. Вогняне жертвоприношення з кунжутом\n4. Тарпана предкам водою з кунжутом\n5. Вживання кунжуту в їжу\n6. Роздача кунжуту іншим\n\n**Молитва:**\n«О Господь Джанардана! О найбільш милостивий Господь Крішна, Ти — рятівник грішників...»\n\n**Підношення:**\n• Кунжутні зерна\n• Дарунки брахманам\n• Чорна корова (за можливістю)',

  recommended_activities_en = E'**Six uses of sesame:**\n\n1. Bathing in water with sesame\n2. Applying sesame paste to body\n3. Fire sacrifice with sesame\n4. Tarpana to ancestors with sesame water\n5. Eating sesame\n6. Distributing sesame to others\n\n**Prayer:**\n"O Lord Janardana! O most merciful Lord Krishna, You are the savior of sinners..."\n\n**Offerings:**\n• Sesame seeds\n• Gifts to brahmins\n• Black cow (if possible)',

  updated_at = now()

WHERE slug = 'sat-tila-ekadashi';

COMMIT;
