-- Add Jaya Ekadashi full story from Padma Purana
-- Uttara-khanda, Chapter 43

BEGIN;

UPDATE ekadashi_info SET
  glory_text_ua = E'**Падма Пурана, Уттара-кганда, Глава 43**\n\n**Історія Мальявана та Пушпаваті**\n\nУ небесному царстві Індри жили двоє небожителів: Пушпаваті — апсара (небесна танцівниця) та Мальяван — ґандгарва (небесний музикант). Вони були відомі своїми виступами перед Індрою та іншими девами.\n\n**Прокляття**\n\nОдного разу, виступаючи перед Індрою, вони неналежно виконали свій танець та спів. Розгніваний Індра прокляв їх, перетворивши на пішачів (демонів) — потворних істот, що блукають у темряві.\n\n**Випадкове дотримання екадаші**\n\nОпинившись на землі у вигляді пішачів, Мальяван та Пушпаваті не могли знайти ні їжі, ні води. Так сталося, що цей день був екадаші. Хоча вони не мали наміру постити — вони просто не могли знайти їжу — вони мимоволі провели весь день без їжі та води.\n\n**Милість Господа Вішну**\n\nГосподь Вішну (Васудева), побачивши це, зарахував їхній мимовільний піст як справжнє дотримання екадаші. Завдяки **васудева-прасаді** (милості Васудеви) вони були звільнені від прокляття та повернули свої небесні форми ґандгарви та апсари.\n\n**Глибинний зміст**\n\nЦя історія демонструє надзвичайну силу екадаші-врати та безмежну милість Бгаґавана Вішну:\n\n• Навіть **ненавмисне** дотримання екадаші приносить благо\n• **Милість Васудеви** перевершує механічне виконання ритуалів\n• **Вайшнавська відданість** важливіша за сувору ведичну обрядовість\n• Господь Вішну — **океан милості**, на відміну від мстивого Індри\n\n**Благословення:**\n\n«Той, хто дотримується Джая Екадаші, здобуває перемогу (джая) над внутрішніми ворогами — похіттю, гнівом та жадібністю — і досягає вищого царства.»',

  glory_text_en = E'**Padma Purana, Uttara-khanda, Chapter 43**\n\n**The Story of Malyavan and Pushpavati**\n\nIn Indra''s celestial kingdom lived two celestial beings: Pushpavati—an apsara (celestial dancer) and Malyavan—a gandharva (celestial musician). They were renowned for their performances before Indra and other devas.\n\n**The Curse**\n\nOnce, while performing before Indra, they improperly executed their dance and song. Angered, Indra cursed them, transforming them into pisachas (demons)—hideous creatures wandering in darkness.\n\n**Unintentional Observance of Ekadashi**\n\nFinding themselves on earth as pisachas, Malyavan and Pushpavati could find neither food nor water. It so happened that this day was Ekadashi. Although they had no intention of fasting—they simply could not find food—they inadvertently spent the entire day without food or water.\n\n**Lord Vishnu''s Mercy**\n\nLord Vishnu (Vasudeva), seeing this, credited their unintentional fast as genuine observance of Ekadashi. Through **Vasudeva-prasada** (the mercy of Vasudeva), they were liberated from the curse and regained their celestial forms as gandharva and apsara.\n\n**Deeper Meaning**\n\nThis story demonstrates the extraordinary power of Ekadashi-vrata and the boundless mercy of Bhagavan Vishnu:\n\n• Even **unintentional** observance of Ekadashi brings benediction\n• **Vasudeva''s mercy** transcends mechanical ritual performance\n• **Vaishnava devotion** surpasses strict Vedic ritualism\n• Lord Vishnu is an **ocean of mercy**, unlike vengeful Indra\n\n**Benediction:**\n\n"One who observes Jaya Ekadashi achieves victory (jaya) over internal enemies—lust, anger, and greed—and attains the supreme kingdom."',

  story_ua = E'Мальяван та Пушпаваті були небесними артистами — ґандгарвою та апсарою, що виступали при дворі Індри. Одного разу вони неналежно виконали свій номер, і розгніваний Індра прокляв їх, перетворивши на пішачів.\n\nБлукаючи землею у потворних формах, вони не могли знайти їжі. Випадково це був день екадаші, і вони мимоволі провели його голодними.\n\nГосподь Вішну, сповнений милості, зарахував цей ненавмисний піст як справжнє дотримання екадаші. Завдяки Його милості (васудева-прасада) прокляття було знято, і вони повернулися до своїх небесних форм.\n\nЦя історія показує, що милість Господа Вішну перевершує сувору обрядовість, і навіть ненавмисне дотримання екадаші приносить звільнення.',

  story_en = E'Malyavan and Pushpavati were celestial performers—a gandharva and apsara who performed at Indra''s court. Once they improperly executed their performance, and angry Indra cursed them, transforming them into pisachas.\n\nWandering the earth in hideous forms, they could not find food. By chance it was the day of Ekadashi, and they inadvertently spent it hungry.\n\nLord Vishnu, full of mercy, credited this unintentional fast as genuine observance of Ekadashi. Through His mercy (Vasudeva-prasada), the curse was lifted, and they returned to their celestial forms.\n\nThis story shows that Lord Vishnu''s mercy transcends strict ritualism, and even unintentional observance of Ekadashi brings liberation.',

  benefits_ua = E'• Перемога (джая) над внутрішніми ворогами\n• Звільнення від похоті, гніву та жадібності\n• Досягнення вищого царства\n• Навіть ненавмисне дотримання приносить благо\n• Милість Господа Вішну (васудева-прасада)',

  benefits_en = E'• Victory (jaya) over internal enemies\n• Liberation from lust, anger, and greed\n• Attainment of the supreme kingdom\n• Even unintentional observance brings benediction\n• Mercy of Lord Vishnu (Vasudeva-prasada)',

  presiding_deity_ua = 'Господь Вішну (Васудева)',
  presiding_deity_en = 'Lord Vishnu (Vasudeva)',

  recommended_activities_ua = E'• Повний піст без їжі та води (якщо можливо)\n• При слабкості дозволено: фрукти, горіхи, овочеві супи (без часнику та цибулі)\n• Слухання історії Мальявана та Пушпаваті\n• Медитація на милість Васудеви\n• Оспівування святих імен',

  recommended_activities_en = E'• Complete fast without food or water (if possible)\n• If weak, permitted: fruits, nuts, vegetable soups (without garlic and onions)\n• Hearing the story of Malyavan and Pushpavati\n• Meditation on Vasudeva''s mercy\n• Chanting the holy names',

  updated_at = now()

WHERE slug = 'jaya-ekadashi';

-- ============================================
-- VIJAYA EKADASHI - Lord Rama's Victory
-- Padma Purana, Uttara-khanda, Chapter 44
-- ============================================

UPDATE ekadashi_info SET
  glory_text_ua = E'**Падма Пурана, Уттара-кганда, Глава 44**\n\n**Екадаші воїнів та правителів**\n\nВіджая Екадаші випадає на темну половину місяця Пхалґуна (лютий-березень). Слово «віджая» санскритом означає «тріумф» або «перемога». Цей екадаші особливо призначений для **кшатріїв** (воїнів та правителів).\n\n**Історія Господа Рами**\n\nЗгідно з Падма Пураною, Господь Рама звернувся до мудреця Бакадалбг''ї, коли зіткнувся з перешкодою — потрібно було перетнути океан, щоб дістатися до Равани на Ланці.\n\nМудрець порадив дотримуватись Віджая Екадаші як духовного засобу, передбачивши, що ця практика забезпечить Рамі перемогу над демоном. Господь Рама не лише сам дотримувався цієї поради, але й наказав своїм воєначальникам та всій армії дотримуватись цього екадаші.\n\n**Результат:** Після дотримання Віджая Екадаші був збудований міст на Ланку, і Рама переміг Равану.\n\n**Особливий протокол для кшатріїв**\n\n**Дашамі (10-й день):**\nПриготувати посудину із золота, срібла, міді або глини, наповнену сімома видами зерна, зверху — ячмінь. Поставити на неї золоте Божество Нараяни.\n\n**Екадаші (11-й день):**\nПоклонятися золотому Божеству підношеннями: горіхами бетелю, кокосами, сандалом та ароматичними препаратами. Брахмани читають вайшнавські вчення протягом дня. Вночі кшатрія тримає неспання з ґгі-лампадами та повторює вайшнавські мантри, підтримуючи лампаду всю ніч.\n\n**Двадаші (12-й день):**\nНа світанку перенести посудину до ріки або струмка та продовжити поклоніння. Подарувати посудину вченому брахману, який знає Веди, та зробити щедрі пожертви.\n\n**Благословення:**\n\n«Ті, хто дотримується цього екадаші, здобувають перемогу в цьому житті та вищі царства після смерті. Просто слухання або обговорення слави Віджая Екадаші знищує всі гріхи та дарує плоди, рівні виконанню ведичного жертвоприношення Ваджапея.»',

  glory_text_en = E'**Padma Purana, Uttara-khanda, Chapter 44**\n\n**Ekadashi for Warriors and Rulers**\n\nVijaya Ekadashi falls on the dark fortnight of Phalguna month (February-March). The word "vijaya" translates from Sanskrit as "triumph" or "victory." This Ekadashi is specifically prescribed for **Kshatriyas** (warriors and rulers).\n\n**The Story of Lord Rama**\n\nAccording to the Padma Purana, Lord Rama sought guidance from the sage Bakadalbhya when facing the obstacle of crossing the ocean to reach Ravana in Lanka.\n\nThe sage recommended observing Vijaya Ekadashi as a spiritual remedy, predicting that this practice would ensure Rama''s victory over the demon. Not only did Lord Rama follow this guidance, but he also ensured his military generals and entire army observed it as well.\n\n**Result:** After observing Vijaya Ekadashi, the bridge to Lanka was built, and Rama defeated Ravana.\n\n**Special Protocol for Kshatriyas**\n\n**Dashami (10th day):**\nPrepare a vessel of gold, silver, copper, or clay filled with seven types of grains, topped with barley. Place a golden deity of Narayana upon it.\n\n**Ekadashi (11th day):**\nWorship the golden deity with offerings of betel nuts, coconuts, sandalwood, and aromatic preparations. Brahmin priests recite Vaishnava teachings during the day. At night, the kshatriya maintains a vigil with ghee lamps and chants Vaishnava mantras, keeping the lamp burning throughout.\n\n**Dvadashi (12th day):**\nAt sunrise, move the vessel to a river or stream and continue worship. Gift the vessel to a Veda-learned Brahmin and make generous donations.\n\n**Benediction:**\n\n"Those observing this Ekadashi gain victory in their current life and higher realms after death. Simply hearing about or discussing Vijaya Ekadashi''s glory destroys all sins and yields fruits equivalent to performing the Vajapeya Vedic sacrifice."',

  story_ua = E'Коли Господь Рама готувався до походу на Ланку, щоб визволити Сіту з полону Равани, Він зіткнувся з величезною перешкодою — океаном, який відділяв Його від острова демонів.\n\nГосподь Рама звернувся до мудреця Бакадалбг''ї за порадою. Мудрець сказав: «Дотримуйся Віджая Екадаші разом зі своєю армією, і перемога буде твоєю».\n\nРама та всі Його воїни, включаючи Ханумана та армію ванарів, дотримувались цього екадаші з великою відданістю. Після цього океан поступився, міст на Ланку був збудований, і Господь Рама переміг демона Равану, звільнивши Сіту.\n\nЦя історія демонструє силу Віджая Екадаші — екадаші, що дарує перемогу навіть у найскладніших ситуаціях.',

  story_en = E'When Lord Rama was preparing for the campaign to Lanka to rescue Sita from Ravana''s captivity, He faced a tremendous obstacle—the ocean that separated Him from the island of demons.\n\nLord Rama sought counsel from the sage Bakadalbhya. The sage said: "Observe Vijaya Ekadashi along with your army, and victory will be yours."\n\nRama and all His warriors, including Hanuman and the army of vanaras, observed this Ekadashi with great devotion. Afterward, the ocean yielded, the bridge to Lanka was built, and Lord Rama defeated the demon Ravana, liberating Sita.\n\nThis story demonstrates the power of Vijaya Ekadashi—the Ekadashi that grants victory even in the most difficult situations.',

  benefits_ua = E'• Особлива перемога (віджая) в усіх починаннях\n• Успіх у важких ситуаціях\n• Благословення Господа Рами\n• Плоди, рівні жертвоприношенню Ваджапея\n• Вищі царства після смерті\n• Знищення всіх гріхів через слухання слави',

  benefits_en = E'• Special victory (vijaya) in all endeavors\n• Success in difficult situations\n• Blessings of Lord Rama\n• Fruits equivalent to Vajapeya sacrifice\n• Higher realms after death\n• Destruction of all sins through hearing the glory',

  presiding_deity_ua = 'Господь Рама (Нараяна)',
  presiding_deity_en = 'Lord Rama (Narayana)',

  recommended_activities_ua = E'**Для кшатріїв (воїнів, правителів):**\n\n**Дашамі:**\n• Приготувати посудину з 7 видами зерна\n• Встановити Божество Нараяни\n\n**Екадаші:**\n• Піст\n• Поклоніння Божеству (горіхи бетелю, кокоси, сандал)\n• Слухання вайшнавських вчень\n• Нічне неспання з ґгі-лампадами\n• Повторення мантр\n\n**Двадаші:**\n• Поклоніння біля води\n• Дарування посудини брахману\n• Щедрі пожертви',

  recommended_activities_en = E'**For Kshatriyas (warriors, rulers):**\n\n**Dashami:**\n• Prepare vessel with 7 types of grains\n• Install Deity of Narayana\n\n**Ekadashi:**\n• Fasting\n• Deity worship (betel nuts, coconuts, sandalwood)\n• Hearing Vaishnava teachings\n• Night vigil with ghee lamps\n• Chanting mantras\n\n**Dvadashi:**\n• Worship near water\n• Gifting vessel to a brahmana\n• Generous donations',

  updated_at = now()

WHERE slug = 'vijaya-ekadashi';

-- ============================================
-- PRABODHINI (HARIBODHINI) EKADASHI
-- Lord Vishnu Awakens - End of Chaturmasya
-- Padma Purana, Uttara-khanda, Chapter 37
-- ============================================

UPDATE ekadashi_info SET
  glory_text_ua = E'**Падма Пурана, Уттара-кганда, Глава 37**\n\n**Пробудження Господа Ґовінди**\n\nПрабодхіні Екадаші, також відомий як Харібодхіні Екадаші, відзначає «пробудження Господа Ґовінди» у світлу половину місяця Картіка. Цей день знаменує момент, коли «Господь Вішну прокидається та спонукає істот до праведних діянь».\n\n**Кінець Чатурмасья**\n\nЦей екадаші завершує чотиримісячний період Чатурмасья, що почався з Девашаяні Екадаші. Протягом цих чотирьох місяців Господь Вішну «спав» на Шеша-назі в молочному океані.\n\n**Найвища заслуга**\n\nУ писанні сказано: «Тисячі жертвоприношень Ашвамедха та сотні Раджасуя не можуть зрівнятися» з благом від дотримання цього єдиного посту з відданістю Господу Вішну.\n\n**Благословення:**\n• Знищення накопичених гріхів за безліч життів\n• Звільнення на Вішну-локу\n• Визволення предків з нижчих царств\n• Дарування процвітання, мудрості, царств та щастя\n\n**Важливість відхі (правил)**\n\n«Навіть мала заслуга, дотримана згідно з належними правилами, стає рівною горі Меру за цінністю», тоді як нехтування процедурами робить результати незначними.\n\n**Тулсі-бгакті: Головний секрет**\n\nЦентральне вчення наголошує на поклонінні Туласі-Деві. Підношення «листя та квітів Туласі Господу Джанардані під час Картіка спалює гріхи, накопичені за мільярди народжень».\n\n**Навадга-Туласі-Бгакті** (дев''ять форм відданості Туласі):\n1. Споглядання Туласі\n2. Доторкання до неї\n3. Медитація на неї\n4. Оспівування її слави\n5. Повторення її імен\n6. Вирощування рослини\n7. Поливання її\n8. Щоденне поклоніння\n9. Підношення Господу Вішну\n\n«Ті, хто виконує це, створюють заслугу, що вимірюється мільярдами Юґ.»',

  glory_text_en = E'**Padma Purana, Uttara-khanda, Chapter 37**\n\n**The Awakening of Lord Govinda**\n\nPrabodhini Ekadashi, also called Haribodhini Ekadashi, commemorates "the awakening of Lord Govinda" during the bright fortnight of Kartik month. This day marks when "Lord Vishnu awakens and prompts beings toward righteous deeds."\n\n**End of Chaturmasya**\n\nThis Ekadashi concludes the four-month period of Chaturmasya that began with Devashayani Ekadashi. During these four months, Lord Vishnu "slept" on Shesha-naga in the milk ocean.\n\n**Supreme Merit**\n\nThe scripture states: "Thousands of Ashvamedha and hundreds of Rajasuya sacrifices cannot equal" the benefits of observing this single fast with devotion to Lord Vishnu.\n\n**Benedictions:**\n• Destroys accumulated sins spanning countless lifetimes\n• Grants liberation on Vishnu-Loka\n• Liberates one''s ancestors from lower realms\n• Bestows prosperity, wisdom, kingdoms, and happiness\n\n**Importance of Vidhi (Rules)**\n\n"Even small merit observed according to proper rules becomes equivalent to Mount Meru in value," while neglecting procedures renders results negligible.\n\n**Tulasi Devotion: The Primary Secret**\n\nThe central teaching emphasizes Tulasi-Devi worship. Offering "Tulasi leaves and flowers to Lord Janardana during Kartik burns sins accumulated over billions of births."\n\n**Navadha-Tulasi-Bhakti** (nine-fold Tulasi devotion):\n1. Seeing Tulasi\n2. Touching her\n3. Meditating upon her\n4. Singing her glories\n5. Reciting her names\n6. Cultivating the plant\n7. Watering her\n8. Daily worship\n9. Offering to Lord Vishnu\n\n"Practitioners performing these create merit measured in billions of Yugas."',

  story_ua = E'Після чотирьох місяців Чатурмасья, коли Господь Вішну відпочивав на кільцях Шеша-наґи в молочному океані, настає день Його пробудження — Прабодхіні Екадаші.\n\nУ цей день Господь Ґовінда прокидається і знову починає активно сприяти духовному прогресу живих істот. Це найсприятливіший день для початку нових справ, весіль та інших благих починань, що були відкладені на час Чатурмасья.\n\nОсобливо в цей день рекомендується поклоніння Туласі-Деві — дев''ять форм відданості їй приносять неймовірну заслугу. Підношення листя Туласі Господу Вішну під час Картіка спалює гріхи мільярдів народжень.',

  story_en = E'After four months of Chaturmasya, when Lord Vishnu rested on the coils of Shesha-naga in the milk ocean, comes the day of His awakening—Prabodhini Ekadashi.\n\nOn this day Lord Govinda awakens and again begins to actively promote the spiritual progress of living beings. This is the most auspicious day for beginning new ventures, weddings, and other auspicious undertakings that were postponed during Chaturmasya.\n\nEspecially on this day, worship of Tulasi-Devi is recommended—nine forms of devotion to her bring incredible merit. Offering Tulasi leaves to Lord Vishnu during Kartik burns sins of billions of births.',

  benefits_ua = E'• Кінець Чатурмасья — нові починання\n• Заслуга понад тисячі Ашвамедха-ягій\n• Знищення гріхів безлічі життів\n• Звільнення на Вішну-локу\n• Визволення предків\n• Процвітання, мудрість, щастя\n• Дев''ять форм Туласі-бгакті — мільярди Юґ заслуги',

  benefits_en = E'• End of Chaturmasya—new beginnings\n• Merit exceeding thousands of Ashvamedha sacrifices\n• Destruction of sins from countless lifetimes\n• Liberation on Vishnu-loka\n• Liberation of ancestors\n• Prosperity, wisdom, happiness\n• Nine forms of Tulasi-bhakti—billions of Yugas of merit',

  presiding_deity_ua = 'Господь Вішну (пробуджений), Туласі-Деві',
  presiding_deity_en = 'Lord Vishnu (awakened), Tulasi-Devi',

  recommended_activities_ua = E'**Основні практики:**\n• Піст\n• Нічне неспання з поклонінням Господу Вішну\n• Поклоніння Туласі-Деві (9 форм)\n• Читання Бгаґавата Пурани\n\n**Підношення:**\n• Листя та квіти Туласі\n• Листя кетакі, аґасті, манго\n\n**Початок нових справ:**\n• Весілля\n• Нові проекти\n• Благі починання',

  recommended_activities_en = E'**Main practices:**\n• Fasting\n• Night vigil with worship of Lord Vishnu\n• Worship of Tulasi-Devi (9 forms)\n• Reading Bhagavata Purana\n\n**Offerings:**\n• Tulasi leaves and flowers\n• Ketaki, Agasti, mango leaves\n\n**Beginning new ventures:**\n• Weddings\n• New projects\n• Auspicious undertakings',

  updated_at = now()

WHERE slug = 'prabodhini-ekadashi';

-- ============================================
-- SAPHALA EKADASHI - Fruits for Vishnu
-- Padma Purana, Uttara-khanda, Chapter 40
-- ============================================

UPDATE ekadashi_info SET
  glory_text_ua = E'**Падма Пурана, Уттара-кганда, Глава 40**\n\n**Екадаші успіху**\n\nСапхала означає «успішний» або «плодотворний». Цей екадаші дарує успіх у всіх починаннях та особливо пов''язаний з підношенням фруктів Господу Вішну.\n\n**Історія Лумпаки**\n\nУ писанні розповідається про Лумпаку — грішного сина царя Магішмати. Він був настільки зіпсованим, що батько вигнав його з царства. Лумпака жив у лісі, полюючи та грабуючи.\n\nОдного разу, блукаючи голодним у холодну ніч екадаші, він заночував під деревом біля храму Господа Вішну. Не маючи їжі, він мимоволі постив, а холод не давав йому заснути — так він провів ніч біля Божества.\n\nЗавдяки цьому ненавмисному дотриманню екадаші його серце очистилось. Він усвідомив свої гріхи, розкаявся і став великим відданим Господа.\n\n**Рекомендовані фрукти для підношення:**\n• Кокоси\n• Горіхи бетелю\n• Цитрусові (помело)\n• Цитрон\n• Гранати\n• Амла (священний плід дгатрі)\n• Гвоздичні плоди\n• Ягоди зізіфуса (китайські фініки)\n• **Манго** (особливо рекомендовано)\n\n**Практика:**\n«Поклоняйтесь Вішну, промовляючи Його (різні) Імена» разом з підношенням фруктів. Читання «108 Імен Шрі Нарасімхи» та вішну-мантр є частиною дотримання.',

  glory_text_en = E'**Padma Purana, Uttara-khanda, Chapter 40**\n\n**Ekadashi of Success**\n\nSaphala means "successful" or "fruitful." This Ekadashi grants success in all endeavors and is especially associated with offering fruits to Lord Vishnu.\n\n**The Story of Lumpaka**\n\nThe scripture tells of Lumpaka—the sinful son of King Mahishmati. He was so corrupt that his father banished him from the kingdom. Lumpaka lived in the forest, hunting and robbing.\n\nOnce, wandering hungry on a cold Ekadashi night, he took shelter under a tree near a temple of Lord Vishnu. Having no food, he inadvertently fasted, and the cold kept him awake—thus he spent the night near the Deity.\n\nThrough this unintentional observance of Ekadashi, his heart became purified. He realized his sins, repented, and became a great devotee of the Lord.\n\n**Recommended fruits for offering:**\n• Coconuts\n• Betel nuts\n• Citrus fruits (pomelo)\n• Citron\n• Pomegranates\n• Amla (sacred dhatri-fruit)\n• Clove fruits\n• Ziziphus berries (Chinese dates)\n• **Mangoes** (especially recommended)\n\n**Practice:**\n"Worship Vishnu by uttering His (various) Names" alongside fruit offerings. Reading "108 Names of Sri Narasimha" and Vishnu mantras is part of observance.',

  story_ua = E'Лумпака був грішним сином царя Магішмати. Через свою розпусту та злочини він був вигнаний батьком і жив у лісі, грабуючи подорожніх.\n\nОднієї холодної ночі, яка випала на екадаші, голодний Лумпака знайшов притулок під деревом біля храму Вішну. Не маючи їжі, він постив, а холод не давав йому заснути — так він провів всю ніч біля Божества.\n\nЦе ненавмисне дотримання екадаші очистило його серце. Вранці він прокинувся іншою людиною — усвідомив свої гріхи та став відданим Господа Вішну.\n\nІсторія Лумпаки показує, що навіть найбільші грішники можуть очиститися завдяки силі екадаші.',

  story_en = E'Lumpaka was the sinful son of King Mahishmati. Due to his debauchery and crimes, he was banished by his father and lived in the forest, robbing travelers.\n\nOne cold night that fell on Ekadashi, hungry Lumpaka found shelter under a tree near a temple of Vishnu. Having no food, he fasted, and the cold kept him awake—thus he spent the entire night near the Deity.\n\nThis unintentional observance of Ekadashi purified his heart. In the morning he awoke a different person—realized his sins and became a devotee of Lord Vishnu.\n\nThe story of Lumpaka shows that even the greatest sinners can be purified through the power of Ekadashi.',

  benefits_ua = E'• Успіх (сапхала) у всіх справах\n• Очищення навіть великих грішників\n• Плоди підношення Вішну\n• Нічне неспання — особлива заслуга\n• Господь приймає дотримання «за силою»',

  benefits_en = E'• Success (saphala) in all matters\n• Purification of even great sinners\n• Fruits of offering to Vishnu\n• Night vigil—special merit\n• Lord accepts observance "according to one''s strength"',

  presiding_deity_ua = 'Господь Нараяна, Шрі Нарасімха',
  presiding_deity_en = 'Lord Narayana, Sri Narasimha',

  recommended_activities_ua = E'• Піст\n• Нічне неспання з повторенням імен Вішну\n• Підношення фруктів: манго, кокоси, гранати, амла\n• Читання 108 Імен Шрі Нарасімхи\n• Повторення вішну-мантр',

  recommended_activities_en = E'• Fasting\n• Night vigil with chanting Vishnu''s names\n• Offering fruits: mangoes, coconuts, pomegranates, amla\n• Reading 108 Names of Sri Narasimha\n• Chanting Vishnu mantras',

  updated_at = now()

WHERE slug = 'saphala-ekadashi';

COMMIT;
