// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeplxgqadcbwlrbgydlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcGx4Z3FhZGNid2xyYmd5ZGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDcyNzUsImV4cCI6MjA3MzY4MzI3NX0.fiA58EYJWNtAzEeG341t98QHmLcY6cwtpgC-TfKx6G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});